### ISSUE TITLE
[문서] To do ✨

### ISSUE THREAD

**Issue by ottl-seo** [ottl-seo/GDSC-Recruiting-FE#8]
그날 할 일을 기록합니닷

**Comment by ottlseo** [comment]
### 22.01.27
- [x] BE: application post api 만들고
- [x] FE: 코드 되는지 테스트 [#9 ]
- [x] 안 되면, FE 코드 전반 수정 (map으로 되어있던거 하나하나 풀기)
- [x] Info 코드 리팩토링

**Comment by ottlseo** [comment]
### 22.01.29
- [x] React Router 개념 학습
- [x] 적용 >> pages, components 로 분리
- [x] 배포를 어떻게 하면 되는지 알아보기
- [x] isCore 여부에 따라 다른 지원서 로드하도록 [#10]
- [x] PR
- [x] 일지 작성

**Comment by ottlseo** [comment]
### 22.01.31
- [x] input 들어오도록, post
- [x] BE: core Apply API만들기 >> [2/2](https://github.com/ottl-seo/GDSC-Recruiting-FE/issues/8#issuecomment-1027063617)
- [x] 코드 리팩토링 (분리)
- [x] (onchange 관리)

**Comment by ottlseo** [comment]
### 22.02.01
- [ ] redux 
- [x] [info POST 오류 해결](https://www.notion.so/22-02-01-47a7f8b311ec4d328f1f605e0bfd9457)
- [x] application POST (core까지) → 글자수 세기와 충돌하지 않도록 명확히 이해하기
- [x] 서버 주소 config 파일로 분리
- [x] 인텔리제이 오류 해결

**Comment by ottlseo** [comment]
### 22.02.02
#### FE
- [ ] 관리자 페이지 만들기 (비동기 get api 적용)
- [x] 메인 페이지 꾸며보기

#### BE
- [x] 코어 지원서 post api 만들기 `/api/application/core`
- [x] 일반멤버 지원서 url 수정 >> `/api/application/general`
- [x] 지원자 리스트 get API 만들기 >> `/api/applicationList/core`, `/general`

**Comment by ottlseo** [comment]
### 22.02.06
- [x] 메인 페이지 
- [x] 반응형 수정
- [x] BE 배포!
- [x] FE: 값 전달 오늘까지 안 되면 하나로 합치기 ..
- [x] 디자이너 연락

**Comment by ottlseo** [comment]
### 22.02.07
- [x] 헤더 생성
- [x] 푸터 생성 :) 윤서 서현 이름 넣기
- [x] 백 배포
- [x] 페이지 간 값 전달 드디어 완료.

**Comment by ottlseo** [comment]
[useHistory](https://www.codegrepper.com/code-examples/javascript/how+to+push+state+with+usehistory)

**Comment by ottlseo** [comment]
### 22.02.08 
- [x] 백 배포 오류 해결
- [x] config 파일 변경
- [x] 반응형 수정중
- [x] info 값도 글자수 제한 적용 -> DB 오류방지 [#25 ]
- [x] api 통신 오류없나 테스트하기

**Comment by ottlseo** [comment]
### 22.02.11 금 
- [x] 서현이 디자인 확인
- [x] 일주일 계획 정리
- [x] 서현이한테 로고 선 따달라고 연락하기
- [ ] CSS 애니메이션 추가

### 22.02.12 토
- [x] BE 배포..!!! 카페 가서 하기
- [x] FE submit 페이지 완성
- [x] footer fix
- [ ] site map 토글 만들어서 넣기
- [ ] 구름 기능 50% 

### 22.02.13 일
- [ ] 종무식 ppt 만들기 
- [x] 안건지 작성
- [x] 17:30 알바, 22:00 모집 회의

**Comment by ottlseo** [comment]
### 22.02.12 디자인 (서현 전달)   
- [x] 다크모드 피드백 요청 (배경색 추천) + 배경 화질 논의
- [ ] Title 글씨체 변경 요청
- [x] 전체적으로 피드백 요청

**Comment by ottlseo** [comment]
### 22.02.13 이후 남은 tasks
#### CSS
- [ ] Title 포인트 적용
- [x] 라디오버튼 수정
- [x] 헤더 수정 >> Grid로 
- [x] 백그라운드 패턴 수정 (이미지가 아니라 css 패턴으로 조정하기)
- [ ] 모바일 화면 꽉 차게
- [x] 푸터 수정 (불투명으로 변경, 이화 로고 넣기)
- [x] 전체적으로 폰트 변경
- [x] main page big Logo >> gif로 변경하고 위로 올라가는 애니메이션 효과
- [x] Title도 애니메이션 효과

### FE 
- [x] 배포 with Github Action
- [x] 코어팀 지원 안받음

#### BE
- [x] 지원서 6개로 DB 수정.....0 API도 수정 배포도 다시

**Comment by ottlseo** [comment]
### 22.02.14
- [x] 404 페이지
- [x] core 지원시 404로 이동
- [x] 라디오버튼
- [x] 모바일 수정..
- [x] info Input Area에 placeholder 추가하기! (ex. 개발 언어)

**Comment by ottlseo** [comment]
프,백 배포
- url: http://gdscewha.s3-website.ap-northeast-2.amazonaws.com/
- [frontend reference](https://blog.appleseed.dev/post/frontend-deploy-on-aws-1/)

**Comment by ottlseo** [comment]
### 22.02.21
- [x]  구글 애널리틱스 추가하기
- [x]  모바일 description 글씨 줄이기
- [x]  재배포
- [x]  DB 확인하고 필요없는 내용 삭제... !
- [x]  가능하면 모든 항목 입력하도록 FE 수정
